# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 02:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=1024)),
                ('provided_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=1024)),
                ('asked_on', models.DateTimeField(auto_now=True)),
                ('about_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watson.Location')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='asked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watson.User'),
        ),
        migrations.AddField(
            model_name='answer',
            name='provided_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watson.User'),
        ),
        migrations.AddField(
            model_name='answer',
            name='to_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watson.Question'),
        ),
    ]
