# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watson', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='asked_by',
            new_name='by_user',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='asked_on',
            new_name='posted_date',
        ),
        migrations.AddField(
            model_name='answer',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(default='OP', max_length=2),
        ),
    ]
